"""adicionar coluna erro_robo

Revision ID: b1f570641464
Revises: fd6805d5eee1
Create Date: 2026-05-19 10:21:40.415675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f570641464'
down_revision: Union[str, Sequence[str], None] = 'fd6805d5eee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissoes', sa.Column('erro_robo', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissoes', 'erro_robo')
    # ### end Alembic commands ###
