"""adicionar campos v2 fornecedores

Revision ID: cd238cea91ae
Revises: cb9b8ff302a7
Create Date: 2026-05-14 08:30:27.498988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd238cea91ae'
down_revision: Union[str, Sequence[str], None] = 'cb9b8ff302a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas_fornecedores', sa.Column('retencao_padrao', sa.Boolean(), nullable=True))
    op.add_column('notas_fornecedores', sa.Column('valor_medio', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('notas_fornecedores', sa.Column('iniciado_em', sa.String(length=7), nullable=True))
    op.add_column('notas_fornecedores', sa.Column('observacoes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas_fornecedores', 'observacoes')
    op.drop_column('notas_fornecedores', 'iniciado_em')
    op.drop_column('notas_fornecedores', 'valor_medio')
    op.drop_column('notas_fornecedores', 'retencao_padrao')
    # ### end Alembic commands ###
