"""adiciona lancamento de notas

Revision ID: e6199e1814e6
Revises: 068e3f9e1759
Create Date: 2026-05-11 08:43:35.474408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6199e1814e6'
down_revision: Union[str, Sequence[str], None] = '068e3f9e1759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cbs_apuracoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbs_apuracoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('iniciada_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ambiente', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cnpj_consultado', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('tiquete_inicial', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tiquete_download', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('erro_codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('erro_mensagem', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('json_resposta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('atualizada_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('cbs_apuracoes_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cbs_apuracoes_pkey'))
    )
    # ### end Alembic commands ###
