"""baseline schema completo

Revision ID: fdeee52be543
Revises: 
Create Date: 2026-06-02 13:39:31.726369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdeee52be543'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('empresa', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_custo_codigo'), 'centros_custo', ['codigo'], unique=True)
    op.create_table('faq_perguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('pergunta', sa.String(length=500), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_perguntas_modulo'), 'faq_perguntas', ['modulo'], unique=False)
    op.create_table('lancamentos_notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True),
    sa.Column('numero_nota', sa.String(length=20), nullable=True),
    sa.Column('serie', sa.String(length=5), nullable=True),
    sa.Column('tipo_nota', sa.String(length=20), nullable=True),
    sa.Column('fornecedor_cnpj', sa.String(length=20), nullable=True),
    sa.Column('fornecedor_nome', sa.String(length=255), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('dados_xml', sa.JSON(), nullable=True),
    sa.Column('dados_complementares', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.Column('screenshot_erro', sa.String(length=500), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamentos_notas_chave_acesso'), 'lancamentos_notas', ['chave_acesso'], unique=False)
    op.create_table('notas_categorias',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_unidades',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('short', sa.String(length=10), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operacoes_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operacoes_nota_codigo'), 'operacoes_nota', ['codigo'], unique=True)
    op.create_table('submissoes',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('tentativa', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('dados_json', sa.JSON(), nullable=True),
    sa.Column('docs_enviados', sa.JSON(), nullable=True),
    sa.Column('motivos_reprovacao', sa.JSON(), nullable=True),
    sa.Column('erro_robo', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('cargo', sa.String(length=20), nullable=True),
    sa.Column('permissoes', sa.JSON(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('assunto', sa.String(length=255), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamados_protocolo'), 'chamados', ['protocolo'], unique=True)
    op.create_table('execucoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=150), nullable=True),
    sa.Column('robo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('duracao_seg', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('categoria_id', sa.String(length=50), nullable=False),
    sa.Column('unidade_id', sa.String(length=20), nullable=False),
    sa.Column('dia_esperado', sa.Integer(), nullable=False),
    sa.Column('retencao_padrao', sa.Boolean(), nullable=True),
    sa.Column('valor_medio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('iniciado_em', sa.String(length=7), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['notas_categorias.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['notas_unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chamados_anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chamados_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('status_anterior', sa.String(length=20), nullable=True),
    sa.Column('status_novo', sa.String(length=20), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('fornecedor_recorrente_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('categoria_id', sa.String(length=50), nullable=False),
    sa.Column('unidade_id', sa.String(length=20), nullable=False),
    sa.Column('dia_esperado', sa.Integer(), nullable=False),
    sa.Column('recebida_em', sa.Date(), nullable=True),
    sa.Column('nf_numero', sa.String(length=50), nullable=True),
    sa.Column('valor_liquido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('retencao', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('avulsa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['notas_categorias.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_recorrente_id'], ['notas_fornecedores.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['notas_unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notas_mes_ano', 'notas', ['mes', 'ano'], unique=False)
    op.create_index('ix_notas_unidade_mes_ano', 'notas', ['unidade_id', 'mes', 'ano'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    op.drop_index('ix_notas_unidade_mes_ano', table_name='notas')
    op.drop_index('ix_notas_mes_ano', table_name='notas')
    op.drop_table('notas')
    op.drop_table('chamados_historico')
    op.drop_table('chamados_anexos')
    op.drop_table('notas_fornecedores')
    op.drop_table('execucoes')
    op.drop_index(op.f('ix_chamados_protocolo'), table_name='chamados')
    op.drop_table('chamados')
    op.drop_table('usuarios')
    op.drop_table('submissoes')
    op.drop_index(op.f('ix_operacoes_nota_codigo'), table_name='operacoes_nota')
    op.drop_table('operacoes_nota')
    op.drop_table('notas_unidades')
    op.drop_table('notas_categorias')
    op.drop_index(op.f('ix_lancamentos_notas_chave_acesso'), table_name='lancamentos_notas')
    op.drop_table('lancamentos_notas')
    op.drop_index(op.f('ix_faq_perguntas_modulo'), table_name='faq_perguntas')
    op.drop_table('faq_perguntas')
    op.drop_index(op.f('ix_centros_custo_codigo'), table_name='centros_custo')
    op.drop_table('centros_custo')
    # ### end Alembic commands ###
